variables:
  system.debug: true

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Webpack build'

  - script: npm test
    displayName: 'Run tests'
    env:
      BROWSER_STACK_ACCESS_KEY: $(BROWSER_STACK_ACCESS_KEY)
      BROWSER_STACK_USERNAME: $(BROWSER_STACK_USERNAME)
      BUNDLEWATCH_GITHUB_TOKEN: $(BUNDLEWATCH_GITHUB_TOKEN)
      SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
      SAUCE_USERNAME: $(SAUCE_USERNAME)
      TEST_BROWSERS: 'ChromeHeadlessNoSandbox,FirefoxHeadless,sl_edge,sl_safari,sl_ios_safari,bs_android_chrome'

  - task: PublishTestResults@2
    displayName: 'Save test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(System.DefaultWorkingDirectory)/junit/*.xml'

  - task: PublishCodeCoverageResults@1
    displayName: 'Save code coverage'
    condition: and(succeededOrFailed(), ne(variables['system.pullrequest.isfork'], true))
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'

  - script: npm pack
    displayName: 'Prepare installable tarball'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Save npm-tarball.tgz'
    condition: and(succeededOrFailed(), ne(variables['system.pullrequest.isfork'], true))
    inputs:
      artifactName: 'npm-tarball.tgz'
      PathtoPublish: '$(System.DefaultWorkingDirectory)/isomorphic-git-lightning-fs-0.0.0-development.tgz'

  - script: npm run semantic-release
    displayName: 'Publish to npm'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    env:
      GH_TOKEN: $(GITHUB_TOKEN)
      NPM_TOKEN: $(Npm.Token)
